import {
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Battery,
  Bell,
  Bookmark,
  Briefcase,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clipboard,
  Clock,
  Cloud,
  CloudRain,
  Code,
  Copy,
  CreditCard,
  Database,
  Diamond,
  DollarSign,
  Download,
  Edit,
  File,
  FileText,
  Flag,
  Folder,
  Heart,
  HelpCircle,
  Hexagon,
  Home,
  Image,
  Info,
  Lightbulb,
  Link,
  Lock,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Mic,
  Minus,
  Moon,
  Music,
  Paperclip,
  Phone,
  Play,
  Plus,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShoppingCart,
  Smile,
  Square,
  Star,
  Sun,
  Tag,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Trash,
  Triangle,
  Unlock,
  Upload,
  User,
  Users,
  Video,
  Wifi,
  X,
  XCircle,
  Zap,
} from 'lucide-angular';

export const ICON_REGISTRY: Record<string, unknown> = {
  'alert-circle': AlertCircle,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  battery: Battery,
  bell: Bell,
  bookmark: Bookmark,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  clipboard: Clipboard,
  clock: Clock,
  cloud: Cloud,
  'cloud-rain': CloudRain,
  code: Code,
  copy: Copy,
  'credit-card': CreditCard,
  database: Database,
  diamond: Diamond,
  'dollar-sign': DollarSign,
  download: Download,
  edit: Edit,
  file: File,
  'file-text': FileText,
  flag: Flag,
  folder: Folder,
  heart: Heart,
  'help-circle': HelpCircle,
  hexagon: Hexagon,
  home: Home,
  image: Image,
  info: Info,
  lightbulb: Lightbulb,
  link: Link,
  lock: Lock,
  mail: Mail,
  'map-pin': MapPin,
  menu: Menu,
  'message-circle': MessageCircle,
  mic: Mic,
  minus: Minus,
  moon: Moon,
  music: Music,
  paperclip: Paperclip,
  phone: Phone,
  play: Play,
  plus: Plus,
  'refresh-cw': RefreshCw,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  'shopping-cart': ShoppingCart,
  smile: Smile,
  square: Square,
  star: Star,
  sun: Sun,
  tag: Tag,
  terminal: Terminal,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  trash: Trash,
  triangle: Triangle,
  unlock: Unlock,
  upload: Upload,
  user: User,
  users: Users,
  video: Video,
  wifi: Wifi,
  x: X,
  'x-circle': XCircle,
  zap: Zap,
};

export const ICON_NAMES: readonly string[] = Object.keys(ICON_REGISTRY).sort();

export function toPascal(name: string): string {
  return name
    .split('-')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
}

export const ICON_PROVIDER_MAP: Record<string, unknown> = Object.fromEntries(
  Object.entries(ICON_REGISTRY).map(([name, imp]) => [toPascal(name), imp]),
);
